// This file is auto-generated by scripts/generate-assets.ts
import asset0 from "../../dist/client/xterm.css" with { type: "file" };
import asset1 from "../../dist/client/base.css" with { type: "file" };
import asset2 from "../../dist/client/xterm.js" with { type: "file" };
import asset3 from "../../dist/client/xterm.js.map" with { type: "file" };
import asset4 from "../../fonts/mOsOul Nerd Font.woff2" with { type: "file" };
import asset5 from "../../fonts/Iosevka Nerd Font Mono.woff2" with { type: "file" };
import asset6 from "../../fonts/Topaz8 Amiga1200 Nerd Font.woff2" with { type: "file" };
import asset7 from "../../fonts/MicroKnight Nerd Font.woff2" with { type: "file" };
import asset8 from "../../themes/default/default.css" with { type: "file" };
import asset9 from "../../themes/default/theme.json" with { type: "file" };
import asset10 from "../../themes/amiga/theme.json" with { type: "file" };
import asset11 from "../../themes/amiga/amiga.css" with { type: "file" };
import asset12 from "../../tmux.conf" with { type: "file" };
import asset13 from "../../src/client/index.html" with { type: "file" };

export const embeddedAssets: Record<string, string> = {
  "dist/client/xterm.css": asset0,
  "dist/client/base.css": asset1,
  "dist/client/xterm.js": asset2,
  "dist/client/xterm.js.map": asset3,
  "fonts/mOsOul Nerd Font.woff2": asset4,
  "fonts/Iosevka Nerd Font Mono.woff2": asset5,
  "fonts/Topaz8 Amiga1200 Nerd Font.woff2": asset6,
  "fonts/MicroKnight Nerd Font.woff2": asset7,
  "themes/default/default.css": asset8,
  "themes/default/theme.json": asset9,
  "themes/amiga/theme.json": asset10,
  "themes/amiga/amiga.css": asset11,
  "tmux.conf": asset12,
  "src/client/index.html": asset13,
};
