// This file is auto-generated by scripts/generate-assets.ts
import asset0 from "../../dist/client/xterm.css" with { type: "file" };
import asset1 from "../../dist/client/ghostty.js.map" with { type: "file" };
import asset2 from "../../dist/client/xterm-dev.js.map" with { type: "file" };
import asset3 from "../../dist/client/xterm.js.map" with { type: "file" };
import asset4 from "../../dist/client/xterm.js" with { type: "file" };
import asset5 from "../../dist/client/ghostty.js" with { type: "file" };
import asset6 from "../../dist/client/xterm-dev.js" with { type: "file" };
import asset7 from "../../fonts/IosevkaNerdFontMono-Regular.woff2" with { type: "file" };
import asset8 from "../../fonts/MicroKnight Nerd Font.woff2" with { type: "file" };
import asset9 from "../../fonts/P0TNOoDLE Nerd Font.woff2" with { type: "file" };
import asset10 from "../../fonts/M+1CodeNerdFont-Regular.woff2" with { type: "file" };
import asset11 from "../../fonts/ZedMonoNerdFont-Regular.woff2" with { type: "file" };
import asset12 from "../../fonts/MonomonTallDemo-Regular.woff2" with { type: "file" };
import asset13 from "../../fonts/M+1NerdFont-Regular.woff2" with { type: "file" };
import asset14 from "../../fonts/BlockMonoNerdFont-Thin.woff2" with { type: "file" };
import asset15 from "../../fonts/BlockMonoNerdFont-Regular.woff2" with { type: "file" };
import asset16 from "../../fonts/mOsOul Nerd Font.woff2" with { type: "file" };
import asset17 from "../../fonts/BlockMonoNerdFont-Medium.woff2" with { type: "file" };
import asset18 from "../../fonts/IosevkaNerdFont-Regular.woff2" with { type: "file" };
import asset19 from "../../fonts/mplus-1m-regular.woff2" with { type: "file" };
import asset20 from "../../fonts/Topaz8 Amiga1200 Nerd Font.woff2" with { type: "file" };
import asset21 from "../../fonts/BlockMonoNerdFont-Light.woff2" with { type: "file" };
import asset22 from "../../fonts/mplus-1m-thin.woff2" with { type: "file" };
import asset23 from "../../fonts/AnkaCoder-C75-r.woff2" with { type: "file" };
import asset24 from "../../fonts/Topaz8 Amiga500 Nerd Font.woff2" with { type: "file" };
import asset25 from "../../tmux.conf" with { type: "file" };
import asset26 from "../../src/client/index.html" with { type: "file" };
import asset27 from "../../node_modules/ghostty-web/ghostty-vt.wasm" with { type: "file" };
import asset28 from "../../node_modules/ghostty-web/dist/ghostty-web.umd.cjs" with { type: "file" };
import asset29 from "../../node_modules/ghostty-web/dist/ghostty-vt.wasm" with { type: "file" };
import asset30 from "../../node_modules/ghostty-web/dist/index.d.ts" with { type: "file" };
import asset31 from "../../node_modules/ghostty-web/dist/ghostty-web.js" with { type: "file" };
import asset32 from "../../node_modules/ghostty-web/dist/__vite-browser-external-2447137e.js" with { type: "file" };

export const embeddedAssets: Record<string, string> = {
  "dist/client/xterm.css": asset0,
  "dist/client/ghostty.js.map": asset1,
  "dist/client/xterm-dev.js.map": asset2,
  "dist/client/xterm.js.map": asset3,
  "dist/client/xterm.js": asset4,
  "dist/client/ghostty.js": asset5,
  "dist/client/xterm-dev.js": asset6,
  "fonts/IosevkaNerdFontMono-Regular.woff2": asset7,
  "fonts/MicroKnight Nerd Font.woff2": asset8,
  "fonts/P0TNOoDLE Nerd Font.woff2": asset9,
  "fonts/M+1CodeNerdFont-Regular.woff2": asset10,
  "fonts/ZedMonoNerdFont-Regular.woff2": asset11,
  "fonts/MonomonTallDemo-Regular.woff2": asset12,
  "fonts/M+1NerdFont-Regular.woff2": asset13,
  "fonts/BlockMonoNerdFont-Thin.woff2": asset14,
  "fonts/BlockMonoNerdFont-Regular.woff2": asset15,
  "fonts/mOsOul Nerd Font.woff2": asset16,
  "fonts/BlockMonoNerdFont-Medium.woff2": asset17,
  "fonts/IosevkaNerdFont-Regular.woff2": asset18,
  "fonts/mplus-1m-regular.woff2": asset19,
  "fonts/Topaz8 Amiga1200 Nerd Font.woff2": asset20,
  "fonts/BlockMonoNerdFont-Light.woff2": asset21,
  "fonts/mplus-1m-thin.woff2": asset22,
  "fonts/AnkaCoder-C75-r.woff2": asset23,
  "fonts/Topaz8 Amiga500 Nerd Font.woff2": asset24,
  "tmux.conf": asset25,
  "src/client/index.html": asset26,
  "ghostty-vt.wasm": asset27,
  "dist/ghostty-web.umd.cjs": asset28,
  "dist/ghostty-vt.wasm": asset29,
  "dist/index.d.ts": asset30,
  "dist/ghostty-web.js": asset31,
  "dist/__vite-browser-external-2447137e.js": asset32,
};
