// This file is auto-generated by scripts/generate-assets.ts
import asset0 from "../../dist/client/xterm.css" with { type: "file" };
import asset1 from "../../dist/client/xterm.js.map" with { type: "file" };
import asset2 from "../../dist/client/ghostty.js" with { type: "file" };
import asset3 from "../../dist/client/base.css" with { type: "file" };
import asset4 from "../../dist/client/xterm.js" with { type: "file" };
import asset5 from "../../dist/client/ghostty.js.map" with { type: "file" };
import asset6 from "../../fonts/mOsOul Nerd Font.woff2" with { type: "file" };
import asset7 from "../../fonts/Iosevka Nerd Font Mono.woff2" with { type: "file" };
import asset8 from "../../fonts/Topaz8 Amiga1200 Nerd Font.woff2" with { type: "file" };
import asset9 from "../../fonts/MicroKnight Nerd Font.woff2" with { type: "file" };
import asset10 from "../../themes/default/default.css" with { type: "file" };
import asset11 from "../../themes/default/theme.json" with { type: "file" };
import asset12 from "../../tmux.conf" with { type: "file" };
import asset13 from "../../src/client/index.html" with { type: "file" };
import asset14 from "../../node_modules/ghostty-web/ghostty-vt.wasm" with { type: "file" };
import asset15 from "../../node_modules/ghostty-web/dist/ghostty-web.umd.cjs" with { type: "file" };
import asset16 from "../../node_modules/ghostty-web/dist/ghostty-vt.wasm" with { type: "file" };
import asset17 from "../../node_modules/ghostty-web/dist/index.d.ts" with { type: "file" };
import asset18 from "../../node_modules/ghostty-web/dist/ghostty-web.js" with { type: "file" };
import asset19 from "../../node_modules/ghostty-web/dist/__vite-browser-external-2447137e.js" with { type: "file" };

export const embeddedAssets: Record<string, string> = {
  "dist/client/xterm.css": asset0,
  "dist/client/xterm.js.map": asset1,
  "dist/client/ghostty.js": asset2,
  "dist/client/base.css": asset3,
  "dist/client/xterm.js": asset4,
  "dist/client/ghostty.js.map": asset5,
  "fonts/mOsOul Nerd Font.woff2": asset6,
  "fonts/Iosevka Nerd Font Mono.woff2": asset7,
  "fonts/Topaz8 Amiga1200 Nerd Font.woff2": asset8,
  "fonts/MicroKnight Nerd Font.woff2": asset9,
  "themes/default/default.css": asset10,
  "themes/default/theme.json": asset11,
  "tmux.conf": asset12,
  "src/client/index.html": asset13,
  "ghostty-vt.wasm": asset14,
  "dist/ghostty-web.umd.cjs": asset15,
  "dist/ghostty-vt.wasm": asset16,
  "dist/index.d.ts": asset17,
  "dist/ghostty-web.js": asset18,
  "dist/__vite-browser-external-2447137e.js": asset19,
};
