import { Glob } from "bun";
import path from "path";
import fs from "fs";

const projectRoot = path.resolve(import.meta.dir, "..");
const outputFile = path.join(projectRoot, "src/server/assets-embedded.ts");

async function generate() {
  const assets: { key: string; path: string }[] = [];

  // Add files from dist/
  const distGlob = new Glob("dist/**/*");
  for (const file of distGlob.scanSync(projectRoot)) {
    const fullPath = path.join(projectRoot, file);
    if (fs.statSync(fullPath).isFile()) {
      // Only include the xterm bundle and required css assets.
      const isBundle = file.startsWith("dist/client/") && (
        file.endsWith("xterm.js") ||
        file.endsWith("xterm.css") || file.endsWith("base.css")
      );
      const isMap = file.endsWith(".map");
      const isVendor = file.includes("vendor-xterm");
      
      if (isBundle || isMap || file.startsWith("dist/server/")) {
        if (!isVendor) {
          assets.push({ key: file, path: "../../" + file });
        }
      }
    }
  }

  // Add files from themes/ (recursive — every file in every pack)
  const themesGlob = new Glob("themes/**/*");
  for (const file of themesGlob.scanSync(projectRoot)) {
    if (fs.statSync(path.join(projectRoot, file)).isFile()) {
      assets.push({ key: file, path: "../../" + file });
    }
  }

  // Embed the static tmux binary when present (produced by `make vendor-tmux`).
  // The server extracts it to a temp path at startup and uses it as the
  // default --tmux binary so the bundle is self-contained.
  const tmuxBinPath = path.join(projectRoot, "dist/bin/tmux");
  if (fs.existsSync(tmuxBinPath)) {
    assets.push({ key: "dist/bin/tmux", path: "../../dist/bin/tmux" });
  }

  // Add tmux.conf
  assets.push({ key: "tmux.conf", path: "../../tmux.conf" });

  // Add index.html template
  assets.push({ key: "src/client/index.html", path: "../../src/client/index.html" });

  let code = "// This file is auto-generated by scripts/generate-assets.ts\n// @ts-nocheck — Bun-specific `with { type: 'file' }` import assertions are not understood by tsc.\n";
  assets.forEach((asset, i) => {
    code += `import asset${i} from "${asset.path}" with { type: "file" };\n`;
  });

  code += "\nexport const embeddedAssets: Record<string, string> = {\n";
  assets.forEach((asset, i) => {
    code += `  ${JSON.stringify(asset.key)}: asset${i},\n`;
  });
  code += "};\n";

  fs.writeFileSync(outputFile, code);
  console.log(`Generated ${outputFile} with ${assets.length} assets`);
}

generate();
