import { Glob } from "bun";
import path from "path";
import fs from "fs";

const projectRoot = path.resolve(import.meta.dir, "..");
const outputFile = path.join(projectRoot, "src/server/assets-embedded.ts");

async function generate() {
  const assets: { key: string; path: string }[] = [];

  // Add files from dist/
  const distGlob = new Glob("dist/**/*");
  for (const file of distGlob.scanSync(projectRoot)) {
    if (fs.statSync(path.join(projectRoot, file)).isFile()) {
      assets.push({ key: file, path: "../../" + file });
    }
  }

  // Add files from fonts/
  const fontsGlob = new Glob("fonts/**/*");
  for (const file of fontsGlob.scanSync(projectRoot)) {
    if (fs.statSync(path.join(projectRoot, file)).isFile() && file.endsWith(".woff2")) {
      assets.push({ key: file, path: "../../" + file });
    }
  }

  // Add tmux.conf
  assets.push({ key: "tmux.conf", path: "../../tmux.conf" });

  // Add index.html template
  assets.push({ key: "src/client/index.html", path: "../../src/client/index.html" });

  // Add ghostty-web assets
  try {
    const ghosttyDir = path.dirname(require.resolve("ghostty-web/package.json"));
    const ghosttyWasm = path.join(ghosttyDir, "ghostty-vt.wasm");
    if (fs.existsSync(ghosttyWasm)) {
      assets.push({ key: "ghostty-vt.wasm", path: path.relative(path.join(projectRoot, "src/server"), ghosttyWasm) });
    }
    const ghosttyDist = path.join(ghosttyDir, "dist");
    if (fs.existsSync(ghosttyDist)) {
      const gdistGlob = new Glob("**/*");
      for (const file of gdistGlob.scanSync(ghosttyDist)) {
        const fullPath = path.join(ghosttyDist, file);
        if (fs.statSync(fullPath).isFile()) {
          assets.push({ key: "dist/" + file, path: path.relative(path.join(projectRoot, "src/server"), fullPath) });
        }
      }
    }
  } catch (e) {
    console.warn("ghostty-web not found, skipping its assets");
  }

  let code = "// This file is auto-generated by scripts/generate-assets.ts\n";
  assets.forEach((asset, i) => {
    code += `import asset${i} from "${asset.path}" with { type: "file" };\n`;
  });

  code += "\nexport const embeddedAssets: Record<string, string> = {\n";
  assets.forEach((asset, i) => {
    code += `  ${JSON.stringify(asset.key)}: asset${i},\n`;
  });
  code += "};\n";

  fs.writeFileSync(outputFile, code);
  console.log(`Generated ${outputFile} with ${assets.length} assets`);
}

generate();
